- src/components/common/Card/GridCard.stories.tsx
- src/components/common/Card/GridCard.tsx
- src/components/common/Card/type.ts
- src/hooks/useImageLoadStatus.ts
GridCard UI 컴포넌트를 구현했습니다.
이미지와 스켈레톤 UI 분기처리를 위하여 커스텀 훅을 만들었고, UI 테스트를 위한 스토리북 파일을 추가하였습니다.
각 페이지마다 사용되는 카드 UI에 차이가 존재하여 Card 컴포넌트를 둘 이상으로 나누게 되었습니다.
`GridCard`라는 컴포넌트 네이밍이 의미가 명확하지 않다고 느끼실 수 있는데 아래의 타임 라인에 어떤 고민을 거쳐
Card의 네이밍을 결정하였는지 정리해두었습니다.
[ [노션] Card 컴포넌트 - 개발 Timeline ](https://www.google.com)
최상위 태그를 article 태그로 감싸주었고, 이미지를 fiture태그로 감싸고,
각 타이틀에 h2태그를 사용하여 의미론적인 HTML 작성에 신경썼습니다.
API를 통해 받아오는 이미지 도메인 주소를 알 수 없는 상태이기 때문에 next/image의 Image태그에 `unoptimized` 속성을 사용하였는데,
이미지를 확인하는데로 next.config.js에 도메인 주소를 등록한 뒤에 `unoptimized` 속성을 제거하는 등 수정이 필요합니다.
(현재 unoptimized 속성으로 인해 next/image의 최적화 기능이 동작하지 않습니다.)
state를 사용하여 스켈레톤 UI가 조건부로 출력되도록 설정하였는데, state를 사용하지 않고 props로 전달받는 imageUrl을 사용해도
유사한 분기처리가 가능 했습니다. 이 2가지 방식에는 각각 장단점이 있었는데 쉽게 정리하면
1. state를 사용하면 사용자 경험에 유리하고, 
2. state를 제거하면 코드가 단순해지고 …
> Feat: GridCard 컴포넌트 구현

- src/components/common/Modal/Modal.stories.tsx
- src/components/common/Modal/Modal.tsx
- src/components/common/Modal/type.ts
- src/styles/globals.css
공통으로 사용하기 위한 Modal UI를 구현하였습니다.
- Modal을 크게 3가지로 분류했습니다 (ModalHeader , ModalContent, ModalFooter)
- ModalHeader는 제목을 위한 영역이며, 일정 넓이를 넘어서면 scroll이 생깁니다.
- ModalContent는 내용을 위한 영역이며, 기본적으로 새로 중앙 정렬되게 설정하였습니다. 전체화면 사용시 fullScreen 속성을 추가해야합니다. 일정 높어를 넘어가면 scroll이 생깁니다.
- ModalFooter는 버튼을 위한 영역입니다. 요소의 넓이가 full이 아니고 한 개인 경우 
sm에서는 오른쪽 정렬 md이상은 중앙 정렬되게 만들었습니다.
속성 정리
- Modal
- isOpen(필수)
- onClose(필수)
- noBackdrop 
- noCloseButton
- fullScreen
- className
- ModalHeader
- start
- center
- className
- ModalContent
- className
- ModalFooter
- className
📢 className은 커스텀을 위한 속성입니다
(Deafult)
(noBackdrop)
(noCloseButton)
(fullScreen)
(test:버튼 1개일시)
(test: overflow-y)
(test: overflow-x)
> Feat: modal 컴포넌트 구현

- src/components/common/Card/GridCard.tsx
- src/components/common/Card/ListCard.tsx
`GridCard`와 `ListCard`를 클릭했을 때 페이지 전환되는 주소가 실제 상세 페이지 주소와 동일하게 변경되었습니다.
- 기존 : `href={`/details/${pageId}`}`
- 변경 후 : `href={`social/detail/${pageId}`}`
> Fix: 모임 상세 페이지 실제 URL과 Card컴포넌트에 적용된 Link href가 다른 문제 수정

- src/api/stories/api.ts
- 스토리 아이디를 통한 컨텐츠 병합 함수 추가
- 아무 인자없이 병합되게 하는 게 구현의도랑은 맞지않는 것 같아서 스토리 아이디를 인자로 받습니다.
1. 스토리 아이디를 통해서 해당 스토리의 approved_count 를 조회
2. 컨텐츠에서 해당 스토리의 컨텐츠를 조회
3. 컨텐츠 승인 테이블에서 해당 컨텐츠 아이디를 가진 필드 수를 조회
4. approved_count 와 컨텐츠 승인의 필드 수를 비교
5. 조건 성립시 해당 컨텐츠 상태를 MERGED로 변경
위와 같은 순서의 구조입니다.
(내용)
> Feat: 스토리 아이디를 통한 컨텐츠 병합 함수 추가

- src/app/social/detail/[socialId]/StorySummary.tsx
before
after
일정 뷰포트 아래에서 텍스트 에디터의 좌우 너비가 지나치게 좁아 UX에 해가 되는 부분을 개선하였습니다.
> Refactor: 모임 상세 페이지 소개글 영역에 반응형 padding, margin 적용

- src/components/common/TextEditor/TextEditor.tsx
before (에디터 컨테이너를 초과)
after (내부에서 스크롤 생김)
에디터의 입력 가능한 높이가
- 툴바가 존재할 경우 -> `calc(${editorHeight} - 20px)` (툴바 높이 20px를 제외)
- 툴바가 존재하지 않을 경우 -> editorHeight 그대로 높이 출력
으로 설정되도록 변경하였습니다.
아직 텍스트 에디터가 사용되는 페이지가 모임 상세, 스토리 상세 글쓰기 모달 두 곳뿐이라
다양하게 테스트가 못 이루어졌습니다. 추후 다른 텍스트 에디터 리팩토링 및 버그 픽스와 함께
에디터 높이 설정에 대한 부분도 다시 조정하겠습니다.
> Fix: 모임 상세 페이지의 텍스트 에디터 내부 입력 영역이 에디터 컨테이너를 초과하는 문제 수정

- src/hooks/useClickOutside.ts
요소의 외부 클릭을 감지하기 위한 커스텀 훅입니다.
이런 식으로 ref와 함수를 연결시켜 사용할 수 있습니다.
(드랍다운 사용 예시)
> Feat: 외부 클릭 감지 custom hook

- src/components/common/Modal/Modal.tsx
- src/components/common/Modal/type.ts
Modal이 열릴 시 body의 scroll을 hidden되고 
다시 Modal이 닫히면 body의 scroll이 활성화되게 하였습니다.
- Modal 열릴시 body overflow hidden 추가
- Modal 닫힐시 body overflow hidden 제거
> Fix: Modal 열릴 시 배경 스크롤 제어

- src/app/mypage/page.tsx
로그인 안하고 mypage에 접근하려 할때 로그인 페이지로 이동하게 redirect를 설정해주었습니다.
- 비로그인시 /auths/signin 으로 redirect
> Fix: 비로그인시 mypage에서 로그인페이지로 redirect

- src/app/library/detail/[id]/_components/CreateContentModal.tsx
- src/app/social/detail/[socialId]/StorySummary.tsx
- src/components/common/TextEditor/TextEditor.tsx
- src/types/textEditor.ts
- src/utils/validators/validateEditorContent.ts
1. 소개글은 최소 `10자`이상, 작성한 스토리 컨텐츠는 최소 `20자`이상을 입력해야만 DB에 등록이 가능하도록 설정하였습니다.
2. 사용자가 현재 몇 자를 입력했는 지를 확인하기 위하여 `TextEditor` 컴포넌트에서 `HTML문자열`과 함께 `순수 문자열`을 내보내도록 설정하였습니다.
3. 순수 문자열 `getText()`의 추가로 타입의 길이가 길어지고, 동일한 타입을 중복으로 선언되는 케이스가 많아져서, 전역 `types`폴더에 `TextEditorRef` 타입 선언하고 각 컴포넌트 및 유틸 함수에서 가져오는 방식으로 변경하였습니다.
4. `ref`에서 문자열 추출 및 유효성 검사(ref존재 유무, 글자 수 제한 충족 여부)를 실행하는 공통 유틸리티 함수 추가하였습니다.
소개 글 빈 값 등록을 막는 `fix` 브랜치로 시작했는데, 작업하다보니 욕심이 나서 공통 함수 추가같은 리팩토링 요소까지
해당 PR에 포함됐습니다,, 앞으로 브랜치의 의미를 더 명확하게 가져갈 수 있도록 신경쓰겠습니다
> Fix: 소개글 및 작성글 빈 값으로 요청이 보내지는 문제 수정 (글자 수 제한 적용)

- src/api/story-collaborators/api.ts
- src/api/story-collaborators/type.ts
- src/app/social/createSocialForm/useCreateSocialForm.ts
- src/app/social/detail/[socialId]/SocialOverView.tsx
- src/app/social/detail/[socialId]/page.tsx
- src/app/social/detail/[socialId]/type.ts
- src/hooks/api/teams/useParticipateCollaborator.ts
"모임 참여하기" 버튼을 클릭하면 달램API 모임 참가 요청과 함께, DB `stroy_collaborators`테이블에 사용자 정보가 등록되는
기능을 구현하였습니다.
`useMatation` 커스텀 훅을 사용하여, 호출 성공 시에 `SOCIAL_PARTICIPANTS` key를 가진 API 데이터를 refetch하도록 하였습니다.
특이 사항이라면 명헌님께서 만들어주신 `createCollaborator` 함수의 매개변수를 `data`, `role` 2개의 인자를 받는 기존 방식에서
하나의 객체를 받는 방식으로 변경하였습니다.
이유는 `React Query`의 설계상 제한으로 인해, `useMutation`은 `mutationFn`이 단일 인자만 받도록 강제하기 때문입니다.
즉 아래와 같이 인자를 전달하면 에러가 발생합니다.
```
insertNewCollaborator(
{
story_id: ...,
user_id: ...,
user_name: ...,
joined_at: ...,
},
TEAM_USER_ROLE.MEMBER
);
```
매개변수의 변경으로 기존에 `createCollaborator`를 호출하던 명헌님의 코드(`useCreateSocialForm.ts`)도 하나의 객체로 묶어 값을 전달하도록 변경하였습니다.
> Feat: 모임 참여에 성공하면 DB 테이블에 사용자 정보가 입력되는 기능 구현

- src/constants/queryKey.ts
- src/hooks/api/users/useGetMyInfo.ts
- src/hooks/api/users/usePostSignout.ts
- 로그아웃해도 이전 유저의 정보가 남아 있는 버그 수정했습니다.
- accessToken의 값은 바뀐 것을 확인했습니다.
- 유저 정보가 리액트 쿼리에 의해서 캐싱되고 있는 것이라 판단했습니다.
- logout 성공시에 userInfo 쿼리를 removeQueries로 지워서 버그를 고쳤습니다.
(내용)
> Fix: 다른 아이디로 로그인해도 GNB와 마이페이지에선 회원정보가 변하지 않는 문제

- src/app/library/detail/[id]/_components/CreateContentModal.tsx
- src/app/library/detail/[id]/_components/WritableUserModal.tsx
- src/app/library/detail/[id]/_components/type.ts
스토리 상세 페이지에서 "컨텐츠 작성 UI"가 출력되는 조건을
기존에 `마지막 작성 컨텐츠가 MERGED일 때`뿐만 아니라,
`마지막 작성 컨텐츠가 존재하지 않을 때` 를 추가하여
모임 생성 초기에 컨텐츠가 존재하지 않은 상황에서도 `컨텐츠 작성 UI`가 출력되도록 수정했습니다
> Fix: 모임 생성 직후 작성된 글이 존재하지 않을 때, 컨텐츠 작성이 불가능한 문제 수정

- src/app/library/detail/[id]/_components/CoverPage.tsx
- src/app/library/detail/[id]/_components/SideButtonGroup.tsx
- src/app/library/detail/[id]/page.tsx
-  이전에 작업한 내용과 같습니다. 
- 표지 이미지 컴포넌트 추가했습니다.
- 저번과 마찬가지로 0번째 페이지를 표지로 했습니다.
- 위의 이유로 스토리 상세 페이지 넘버 초기 값을 0으로 설정했습니다.
> Fix: 표지 컴포넌트 추가

- src/hooks/stories/useGetContent.ts
`useQuery`의 `select`옵션을 사용하여
`useGetContent` 호출 시에 `status`가 `MERGED`인 데이터만 가져오도록 필터링하였습니다.
(서버에서 가져올 때부터 필터링을 할 수 있겠지만, `PENDING`인 컨텐츠를 하나 더 가져오는 성능 낭비가 크지 않다고 판단하여
일단은 전체를 가져오고 그 중에 `MERGED` 만 반환하도록 하였습니다.)
현재로써는 `PENDING` 상태인 컨텐츠가 필요할 경우 `useGetLastContent` 훅을 사용하면 됩니다.
차후에 두 요청을 하나로 줄일 수 있을 지 이야기해보면 좋을 것 같습니다.
> Fix: 승인되지 않은 글이 스토리 상세 페이지에 출력되는 문제 수정 (MERGED 된 컨텐츠만 가져오도록 수정)

- src/api/stories/api.ts
- src/hooks/api/content-approvals/useApproveContent.ts
- 승인 정원 이상일 때만 자동 병합 기능
- 승인 인원에 만족하는 마지막 승인시에 자동 병합 기능 추가했습니다.
- 데이터베이스에 우리가 생각한 로직과 다르게 저장된 내용들이 있어서 로직상에는 문제가 없어서도 에러가 발생하는 경우가 있었던 것 같습니다.
- ex) 한 스토리당 pending은 하나밖에 없는데 두개 이상인 경우
(내용)
> Feat: 승인 정원 이상일 때 자동 병합 기능

- src/api/stories/api.ts
- src/app/social/SocialList.tsx
- src/constants/queryKey.ts
- src/hooks/api/stories/useGetSocialSummary.ts
```tsx
queryFn: async () => {
const summaries = await Promise.all(
socialList.map(async (item) => {
const summary = await getSocialSummary(item.id);
return summary;
})
);
return summaries;
},
```
지혁님께서도 사용하셨던 Promise.all을 적용해서 병렬적으로 데이터를 가져올 수 있도록 구현했습니다.
https://github.com/user-attachments/assets/96f4d023-3124-4e4d-ac40-fc8d50063230
> Fix: 모임 요약 데이터 표시

- src/api/story-collaborators/api.ts
- src/app/social/detail/[socialId]/SocialOverView.tsx
- src/hooks/api/teams/useJoinTeam.tsx
- src/hooks/api/teams/useParticipateCollaborator.ts
`navigateStoryOrJoinTeam` 함수의 구조를 개선하였습니다.
중첩된 if문을 줄였고, `try catch` 문을 추가하여 모임 참여 요청에 대한 에러 제어를 가능하도록 하였습니다.
try 내부에서 비동기로 '모임 참여 요청'과 'Collaborators테이블에 사용자 등록'이 이루어질 수 있도록,
두 메서드를 `mutate()`에서 `mutateAsync()` 으로 변경하였습니다. 
'모임에 참여하시겠습니까?' '모임 참여에 성공했습니다' 같은 사용자가 응답 결과를 확인할 수 있는 alert 메시지를 추가하였고,
참여 성공 시에 `UserRole` 쿼리를 무효화하고, 부분 refetch 를 실행해서
권한에 따라 분기 처리 되는 '참여하기' 버튼이 곧바로 '스토리 이어쓰기' 버튼으로 변경되도록 하였습니다.
> Fix: 모임 참여에 성공했을 때, alert출력, UI 반영 적용

- src/app/library/detail/[id]/_components/CreateContentModal.tsx
- src/app/library/detail/[id]/_components/WritableUserModal.tsx
- src/app/library/detail/[id]/_components/type.ts
- src/app/library/detail/[id]/page.tsx
- src/components/common/TextEditor/TextEditor.tsx
- src/components/common/TextEditor/type.ts
`StringLimit`라는 커스텀 Extension을 만들어서 텍스트 에디터 내부의 글자 수 제한을 적용하였습니다.
컨텐츠 작성 시에는 모임장이 설정한 제한 글자 수가 적용되며,
소개글 작성 시에는 기본 값인 최대 2000자 제한이 적용됩니다.
```
{hasReachedLimit && (
<p className="pr-4 text-gray-500">최대 글자 수에 도달하였습니다.</p>
)}
```
위와 같은 HelperText를 적용하여, 사용자에게 글자 상한선 도달 여부를 알리도록 하였습니다.
> Feat: 에디터를 통한 텍스트 작성 시에 글자 수 제한 적용

- src/app/library/detail/[id]/_components/WritableUserModal.tsx
```
if (approveUserData?.length) {
setTempApprovedCount(approveUserData?.length);
}
if (approveUserData && currentUserId) {
```
기존 useEffect 내부에서 승인 인원 수를 업데이트하는 로직은
`approveUserData`로 빈 배열이 들어오면 조건 검사에 실패하여 `tempApprovedCount` 상태를 업데이트하지 않았습니다.
그래서 빈 배열이 들어와도 승인 인원 수를 0으로 업데이트하지 못하는 문제가 있었습니다.
```
if (Array.isArray(approveUserData)) {
setTempApprovedCount(approveUserData.length);
```
변경된 로직은 `approveUserData`가 배열인지 아닌지(undefined인지)만을 검사하여,
배열이라면 내부가 비어있는 여부와는 관계 없이 항상 `tempApprovedCount`를 업데이트하므로
API 응답의 상태를 보다 잘 반영할 수 있게 하였습니다.
현재 개발 환경 테스트에서는 해당 '컨텐츠 등록 직후 승인인원 1 표시' 이슈가 발견되지 않고 있는데
혹시 다시 동일한 문제가 발생하거나 승인 인원 표시 관련한 다른 문제가 발생하면 말씀 부탁드립니다!
> fix: 컨텐츠 등록 직후에 승인 인원수가 0이 아닌 1로 표시되는 문제 수정

- src/components/common/Card/DetailCard.tsx
`isButtonActivate`의 조건 설정
**기존** : `capacity`와 `participantCount`를 비교해서 `capacity`가 더 클때만 활성화
**변경** : 추가적으로 현재 사용자의 권한을 검사하여, `GUEST`일 경우 `capacity`가
더 클 때만(모집 정원이 채워지지 않았을 때만) 활성화,
`MEMBER`또는 `LEADER` 일 때는 항상 활성화
> fix: 모집 정원이 채워졌을 때 이미 모임에 속한 사용자의 '스토리 이어쓰기' 버튼이 비활성화되는 문제 수정

- src/app/social/detail/[socialId]/_components/SocialOverView.tsx
- src/hooks/api/supabase/story-collaborators/useJoinTeam.ts
```
try {
await joinTeam();
await insertNewCollaborator({
data: {
story_id: currentStoryId,
user_id: currentUserId!,
user_name: currentUserName!,
joined_at: new Date().toISOString(),
},
role: TEAM_USER_ROLE.MEMBER,
});
```
기존에 모임 참여 버튼을 클릭하면 위와 같이 비동기적으로 요청이 보내졌고,
모임 참여에 대한 성공 alert는 `joinTeam` Mutation내부의 onSuccess옵션으로 설정되어 있었습니다.
그래서 `joinTeam`은 성공하고, `insertNewCollaborator`는 실패하면
모임 참여 성공 alert가 뜨면서 바로 catch문의 모임 참여 실패 alert가 출력되는 문제가 있었습니다.
Mutation 내부의 alert메시지를 try 문으로 옮겨서 두 요청 모두 성공했을 때만 출력되도록 변경하였습니다.
```
if (!currentUserId || !currentUserName) {
alert('로그인이 필요한 서비스입니다.');
router.push('/auths/signin');
return;
}
const joinTeamConfirmed = window.confirm('모임에 참여하시겠습니까?');
```
또한 기존에 조건문 내부에 return 문이 존재하지 않아서
alert('로그인이 필요한 서비스입니다.') -> confirm('모임에 참여하시겠습니까?') 가 연이어서 출력되는 문제가 있었는데 …
> Fix/#232: 모임 참여 버튼 클릭 시에 서로 다른 alert 가 연달아 출력되는 문제 수정

- src/components/common/TextEditor/TextEditor.tsx
- src/components/common/TextEditor/type.ts
기존에 TipTap 에디터 내부에서 글을 쓰는 실제 영역(.ProseMirror)이 작기 때문에
전체 에디터 컨테이너를 클릭해도 커서가 활성화되지 않는 문제가 있었습니다.
포커스 가능한 영역을 `<EditorContent />` 전체로 확대하여 해당 문제를 해결했습니다.
```
onClick={() => {
if (!editor?.isFocused) {
editor.commands.focus();
}
}}
```
인라인으로 적용된 onClick 이벤트 핸들러와 style속성을 외부 함수로 분리하였습니다.
> Fix/#235: 텍스트 에디터의 아무 위치나 클릭해도 커서(focus)가 활성화되도록 수정

- src/app/not-found.tsx
올바르지 않은 URL로 접근했을 때, 보여지는 `not-found`페이지를 만들었습니다.
각 컴포넌트 및 함수 내부에서
```
import { notFound } from 'next/navigation';
if (!data) notFound() 
```
와 같이 `notFound()` 를 호출할 경우에도 해당 페이지로 연결됩니다.
서버 컴포넌트에서도 정상적으로 동작하기 때문에 필요한 에러처리에 사용해주시면 될 것 같습니다.
> Feature/#255: 전역 NotFound 페이지 추가

- src/app/library/detail/[id]/page.tsx
- src/app/not-found.tsx
- src/app/social/detail/[socialId]/_components/SocialOverView.tsx
- src/components/layout/LayoutWrapper.tsx
기존에는 /auths  경로만 스타일을 다르게 하고 나머지 경로에는 똑같은 스타일을 주었는데 이번에 not-found 페이지와 /library/detail 페이지에 다른 스타일이 적용된 걸 확인하여 설정을 추가했습니다.
[not-found, library/detail]
[social, library, mypage]
[auths]
> Refactor/#261: default layout 설정 추가 및 수정

- src/components/layout/GNB/LoginSection.tsx
- src/components/layout/GNB/UserDropdown.tsx
- GNB 내 프로필 사이즈 조정
- 모든 이미지 rounded 적용되게 상위요소에 적용
(rounded 적용)
> Fix/#246: gnb 프로필 사이즈 수정, rounded 적용

- src/app/library/detail/[id]/_components/PaginatedContentViewer.tsx
- src/app/library/detail/[id]/_components/PaginationControl.tsx
- src/app/library/detail/[id]/hooks/usePaginateContentsByViewport.ts
특정 뷰포트 및 화면 비율에서 컨텐츠와 페이지네이션이 겹쳐 보이는 문제를 수정했습니다.
(특정 조건에서만 발생하는 문제이기도 하고, 최종 발표 전까지 병합하기 어려울 수 있을 것 같아서 hotfix 브랜치로
분류하지는 않았습니다)
1. 모든 뷰포트에서 줄간 간격을 소폭 줄였습니다. (`leading` 클래스)
2. 페이지 이동 네비게이션에서 타이틀과 네비게이션 버튼 사이의 간격을 1rem 줄였습니다.
3. 렌더링된 DOM이 컨텐츠의 높이를 더 정확하게 측정할 수 있도록 상세한 스타일을 적용하였습니다.
DOM이 컨텐츠의 높이를 정확하게 측정하지 못해서 한 페이지 내부에 많은 컨텐츠가 출력
컨텐츠의 높이를 보다 정확하게 측정하여 두 페이지로 나눠서 컨텐츠 출력
> Refactor/#282: 컨텐츠 및 페이지네이션의 반응형 레이아웃 상세화 및 더 정확하게 DOM 렌더링 높이를 측정하도록 개선
