we-write/frontend

package-lock.json, src/components/common/Button/Button.stories.tsx, src/components/common/Button/Button.tsx, src/components/common/Button/type.ts, src/styles/globals.css, src/utils/getColorSystem.ts
버튼컴포넌트를 설계하고 구현했습니다.
badge컴포넌트에서도 사용할 수 있는 getColorSystem 함수를 구현해봤습니다
여러 컴포넌트에서 비슷하게 구현될 수 있는 디자인 시스템을 가져올 수 있도록 재사용함수로 구현해봤습니다,
이번에 저도 처음 알게된 assertUnreachable함수를 통해 에러처리를 하였고,
Badge나 Box 등 다른 컴포넌트에서도 추가할 수 있는 방향으로 설계했습니다.
global.css에서 btn-primary 반대로 전환될때는 btn-primary-inverted로 컨벤션을 정해봐야할거 같아 이 부분은 같이 논의해보겠습니다!
class명이 btn이라고 되어있긴한데 컨벤션이 확정된다면 클래스명을 추상화하여 변경하겠습니다!
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex)
=> Feat: 버튼 컴포넌트 구현

package-lock.json
Mac 과 Windows 사이의 설정 파일 호환성 문제로 발생하는 에러를 수정.
Windwos에서 node.js 실행 환경에 필요한 `.node` 환경 설정들을 수정 및 추가
팀원 모두의 정상 동작 테스트를 거쳤습니다.
=> Chore: Windows 환경에서 발생하는 빌드 에러 해결을 위해 package.lock.josn 동기화

next.config.ts
svgr 관련 이슈로 nextConfig 설정 변경 사항있습니다.
설명은 구두 회의로 생략
(내용)
=> Chore: svgr 이슈 next.config 재설정

.github/workflows/build.yml, src/api/instance.ts, src/components/common/Observer/Observer.tsx
(내용)
Github Actions에서 CI로 빌드 발생했던 오류를 수정했습니다.
1.Github Actions에서 CI로 빌드 시 필요한 환경변수를 정의합니다.
저장소 내에서 secrets에  환경변수를 설정하였습니다
2. throw error시 오타를 발견하여 수정하였습니다.(굳이 하지 않아도 되지만 팀원들과 함께발견해서 수정했습니다.)
3. observer에서 current 부분 warning 이슈 해결
- 원인 설명
`observerRef.current`는 렌더링 중 변경될 수 있습니다.
`useEffect`의 cleanup 함수가 실행될 때는 `observerRef.current`가 **null이거나 다른 값일 가능성**이 있습니다.
그래서 cleanup에서 직접 사용하는 것은 불안정하며 ESLint가 경고합니다.
- 해결
ref 값을 변수에 저장해서 사용했습니다.
=> Feat: CI 환경설정 구문 작성 및 빌드 에러 수정

src/components/common/Chip/Chip.stories.tsx, src/components/common/Chip/Chip.tsx, src/components/common/Chip/type.ts
- chip 컴포넌트 구현
- chip(badge) 컴포넌트 구현했습니다.
- ~small,medium,large로 사이즈를 나눴습니다.~
- ~칩과 뱃지의 차이가 없다고 생각하여 시안중에 badge로 구분된 컴포넌트를 small size로 스타일을 적용했습니다.(가독성과 코드 이해도를 위해 변경이 필요할 것 같으면 말씀해주세요!!)~
-~ 글자 색상,배경 색상,이외에 추가 스타일 옵션으로 설정했습니다.~
- 크게 스타일이 rouded 수치에 따라 다른 것 같아서 default와 rounded 로 변경했습니다.
- 색상은 프로젝트 컬러 시스템으로 변경했습니다.
- 무조건 들어가야할 옵션은 글자가 중앙에 위치하는 것 밖에 없는 것 같은데, custom을 어떤 식으로 주는게 좋을까요? 편하게 말씀해주세요!
=> Feat:Chip 컴포넌트 구현

.github/workflows/build.yml
CI에 필요한 상수를 추가합니다.
BAAS_API_KEY상수를 추가했습니다.
=> Chore: BAAS_API_KEY추가

src/app/layout.tsx, src/components/layout/GNB/GNB.tsx, src/components/layout/GNB/LoginSection.tsx, src/hooks/api/users/useGetMyInfo.ts, src/hooks/api/users/usePostSignin.ts, src/hooks/api/users/usePostSignout.ts, src/providers/userInfoProvider.tsx, src/utils/authContext.tsx
로그인 상태 유지 수정했습니다
- 기존 isSignIn을 최초에는 null 값으로 두고, 로컬 저장소 확인후에
isSignIn을 true로 바꿔서 유저 정보 요청하는 방식입니다.
(내용)
=> fix: 로그인 상태 유지 수정

src/app/social/SocialList.tsx
모임찾기 페이지에서 반응형 스타일을 추가했습니다.
모바일 사이즈에서는 1개
태블릿 사이즈에서는 2개
데스크탑 사이즈에서는 3개로 
카드가 보여지도록 스타일을 주었습니다.
=> Feat: 모임찾기 반응형 스타일 추가

src/components/layout/GNB/LoginSection.tsx, src/components/layout/GNB/UserDropdown.tsx, src/components/layout/GNB/type.ts, src/components/layout/SideDrawer/type.ts, src/hooks/useClickOutside.ts
로그인시 나타나는 gnb에 나타나는 UserDropdown를 구현하였습니다.
메뉴로는 마이페이지, 로그아웃이 있고, route를 연결해줘서 클릭시 해당 route로 이동하게 설정하였습니다.
- 로그인시 프로필 클릭하면 UserDropdown이 나타남
- 마이페이지로 이동, 로그아웃 함수 생성
- 마이페이지에서 로그아웃시 로그인 페이지로 이동
(UserDropdown 구현)
=> Feat: gnb UserDropdown 구현

src/components/layout/GNB/GNB.tsx, src/components/layout/GNB/LoginSection.tsx, src/components/layout/GNB/LogoButton.tsx, src/components/layout/GNB/MenuGroups.tsx, src/components/layout/GNB/UserDropdown.tsx, src/components/layout/GNB/type.ts, src/components/layout/SideDrawer/SideDrawer.tsx, src/components/layout/SideDrawer/type.ts, src/hooks/useClickOutside.ts
기존 SideDrawer가 로그인 여부가 제대로 적용되지 않아 상태를 연결해주고,
SideDrawer가 나타나면 로고가 가려지는 부분이 있어 LogoButton을 가져와 적용하였습니다.
- GNB의 isSignIn으로 로그인 상태 연결
- 로그인, 로그아웃 함수 선언 후 연결
- 로고버튼을 가져와 배치해 적용
=> fix: gnb SideDrawer 로그인 여부 적용, 로고 버튼 추가

src/app/social/createSocialForm/useCreateSocialForm.ts, src/components/common/Calendar/Calendar.tsx
캘린더에서 발생하는 유효성검사 트리거 에러를 수정했습니다.
기본적으로 버튼의 타입은 submit으로 되어있어서 onChange로 되어있는 useForm의 유효성 검사가 실행되어서 에러가 발생했습니다.
그래서 달력 안에있는 모든 버튼의 타입을 'button'으로 설정을 해주었습니다.
https://github.com/user-attachments/assets/b7691893-7d0e-48a7-bc94-9c9f8d057884
=> Fix: 캘린더 유효성 검사 트리거 에러 수정

src/app/library/_components/LibraryListGrid.tsx, src/app/social/SocialList.tsx, src/components/common/Card/GridCard.stories.tsx, src/components/common/Card/GridCard.tsx, src/components/common/Card/type.ts
스토리찾기에서 스토리 상세 페이지 이동 시 에러 발생
- 스토리 찾기에서 스토리 아이디를 가지고 소셜 페이지로 경로가 설정돼서 에러가 발생했었습니다.
- (social/detail/storyId) - > (library/detail/storyId)
- GridCard 컴포넌트 props로 href속성을 추가해서 social 또는 library 값을 받도록 했습니다.
(내용)
=> fix: 스토리 상세 페이지로 경로 변경

src/api/auth.ts, src/app/auths/signup/page.tsx
- 회원 가입시 유효성 오류시 잘못된 메시지가 나오던 버그 수정했습니다.
- 회원 가입시 유효하지않은 이메일 입력시 에러 메시지가 정상적으로 나옵니다
- 비밀번호 공백 제외 8자로 수정했습니다
(내용)
=> Fix: 회원가입 유효성 검사 수정

src/app/auths/signin/page.tsx
로그인 컴포넌트 모바일 간격 조정했습니다
- 로그인 컴포넌트 모바일 간격 조정했습니다
- 기존에 px-1 에서 px-4로 수정했습니다.
=> fix: 로그인 모바일 사이즈 수치 조정

src/app/social/createSocialForm/useCreateSocialForm.ts
기존에 모임id를 저장하고 있었는데 userId를 저장하도록 변경했습니다!
=> Fix: 데이터베이스 저장시 잘못된 id저장 오류 해결

src/hooks/api/teams/useJoinTeam.tsx
모임이 마감되었으면 알림을 하고 뒤로 이동시킵니다.
'모집이 마감된 모임입니다' 라는 에러메세지가 올 경우 뒤로 리다이렉트 시켰습니다!
(내용)
=> Fix: 마감된 모임 처리

src/app/social/detail/[socialId]/SocialOverView.tsx
- 모임 참여 실패후에 db에 저장되는 이슈 수정했습니다
(내용)
```ts
const { mutate: joinTeam, isSuccess: isJoinTeamSuccess } = useJoinTeam({
socialId: currentSocialId,
});
f (isJoinTeamSuccess) {
insertNewCollaborator({
data: {
story_id: currentStoryId,
user_id: currentUserId,
user_name: currentUserName,
joined_at: new Date().toISOString(),
},
role: TEAM_USER_ROLE.MEMBER,
});
}
```
- codeit 참여하기 api 가 성공했을 때, db에도 저장되도록 분기처리 추가했습니다
(내용)
=> Fix: 모임 참여 실패후에 db에 저장되는 이슈

src/hooks/api/content-approvals/useApproveContent.ts
- 승인 인원이 달성됐을 때 실제 병합 처리
```ts
onSuccess: async () => {
await updateContentMerge(storyId);
queryClient.invalidateQueries({
queryKey: [QUERY_KEY.GET_LAST_CONTENT, storyId],
});
queryClient.invalidateQueries({
queryKey: [QUERY_KEY.GET_APPROVE_USER, contentId],
});
setTimeout(() => alert('승인되었습니다.'
```
병합하는 함수가 최신화된 정보를 못 가져온다고 판단하여 비동기처리로 변경했습니다
(내용)
=> fix: 승인 인원이 달성됐을 때 실제 병합 처리

src/api/instance.ts
axios interceptor설정에서 토큰삭제로직을 수정했습니다.
로그아웃 기능에서 deleteCookie가 적용된걸로 보아 클라이언트 사이드에서도 적용이 가능한거 같아 async 구문을 제거했더니 정상적으로 쿠키가 삭제되었습니다.
(내용)
=> Fix: interceptor 토큰 삭제로직 수정

src/app/auths/signin/page.tsx, src/app/auths/signup/page.tsx
- 로그인 완료된 상태에서 로그인/회원가입 페이지로 접속시에 메인 화면으로 리다이렉트합니다.
```ts
const { isSignIn } = useAuth();
useEffect(() => {
if (isSignIn) {
router.push(APP_ROUTES.social);
}
}, []);
if (isSignIn) {
return <div>Loading...</div>;
}
```
- 로그인한 유저가 로그인이나 회원가입 폼에 접근하지 못하게 다른 컴포넌트를 반환했습니다.
- 
(내용)
=> Fix: 로그인시 로그인 페이지 라우팅

src/api/mypage/type.ts, src/app/mypage/myProfile/MyProfile.tsx, src/app/mypage/mySocial/MySocialList.tsx, src/app/mypage/mySocial/SocialListCards.tsx
마이페이지 내 모임 목록에서 삭제된 모임이 보이는 현상이 있었습니다.
팀원과 조율 후 삭제된 모임은 표시되지 않게 수정하였습니다.
- 나의 모임 목록에서 canceledAt으로 filter 추가
=> Fix: mysocialist 내 삭제된 모임 표시 안되게 처리

src/app/social/_components/create-social-form/DropdownInput.tsx, src/app/social/_components/create-social-form/SocialForm.tsx, src/components/common/Dropdown/Dropdown.tsx, src/components/common/Dropdown/type.ts
- 모임 작성하기 내부에 드롭다운 겹침 현상 수정했습니다.
- 겹침 현상을 방지하기 위해서 DropDown 내부에 useClickOutside 훅 추가했습니다.
(내용)
=> Fix: 모임작성하기 드롭다운 겹침 현상

src/api/instance.ts, src/api/social-detail/api.ts, src/app/social/detail/[socialId]/page.tsx
기존 정규식 /^\/gatherings\/\d+$/은 /gatherings/1234까지만 매칭되고, 
/gatherings/1234/participants와 같은 하위 경로는 매칭되지 않았습니다.
이를 해결하기 위해 정규식을 /^\/gatherings\/\d+(\/.*)?$/로 수정하여, 하위 경로가 있어도 매칭되도록 변경했습니다.
로그인을 하지 않은 상태에서 getMyInfo를 호출하니 토큰이 없는 상태에서 호출하여서 에러가 발생했던 문제를
getMyInfoOnServer로 처리하도록 변경했습니다.
=> Fix/#237: instance 에서 발생하는 오류 해결

src/app/auths/signin/page.tsx, src/components/common/Button/Button.tsx, src/components/layout/GNB/LoginSection.tsx, src/components/layout/SideDrawer/SideDrawer.tsx, src/hooks/useReferer.ts
- useReferer 커스텀 훅 제작
- 로그인 관련 부분 적용
- 이전 router 코드 제거 (로그인)
---------------------------------
[로그인 버튼 클릭시]
[로그인시]
[encode한 referer를 보관]
[referer를 가져와 decode후 redirect]
=> Feature/#251: useReferer 커스텀 훅 제작 및 적용

src/app/library/detail/[id]/_components/ContentCover.tsx, src/app/library/detail/[id]/_components/PaginationControl.tsx, src/app/library/detail/[id]/_components/SideButtonGroup.tsx, src/app/library/detail/[id]/page.tsx
- 뒤로가기 버튼이 표지에서만 볼 수 있는 것을 수정했습니다(경로는 논의가 필요할 것 같습니다.)
- 접근성을 위해서 페이지네이션 글씨 밝기를 높게 변경했습니다.
- 이미지 페칭 우선순위를 높이기 위해서 속성 추가했습니다.
(내용)
=> Refactor/#259:  스토리 상세 페이지 표지 컴포넌트 리팩토링

src/app/social/_components/social-filter-bar/DateFilter.tsx, src/app/social/_components/social-filter-bar/GenreFilter.tsx, src/app/social/_components/social-filter-bar/SortByCapacityAndEndDate.tsx
메인 페이지(소셜) 드롭다운 외부 클릭시 닫힘 적용 추가했습니다
(내용)
=> Fix/#270: 소셜 드롭다운 컴포넌트 useClickOutside 반영

jest.config.ts, jest.setup.ts, package-lock.json, package.json
- jest 설치 및 기본 설정
- npm run test로 동작 확인했습니다.
최초에 기술 스택 정할 때 jest 로 결정했던 걸로 기억해서 jest 설치했습니다.
다른 테스트가 적합한 거 같다면 병합하지않고 close하면 될 것 같습니다!!
(내용)
=> Feature/#277: jest 기본 설정

jest.config.ts, package-lock.json, src/app/auths/signup/_components/SignupForm.test.tsx, src/app/auths/signup/_components/SignupForm.tsx, src/components/common/Input/Input.tsx
- 회원가입 유효성 검사 테스트 코드 추가했습니다.
- 비밀번호 표시 아이콘은 jest가 svg 인식을 못해서 lucide icon으로 변경했습니다.
- 이메일 중복검사는 추후에 추가하도록 하겠습니다.
(내용)
=> Feature/#279: 회원 가입 폼 유효성 검사 테스트 코드 추가
